name: btcs_web_wallet
description: Simple Bitcoin Silver web wallet - Load, Send, Receive
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # Core crypto libraries (web compatible)
  pointycastle: ^3.9.1
  crypto: ^3.0.1
  bech32: ^0.2.2
  bip32: ^2.0.0
  http: ^1.2.2
  hex: ^0.2.0
  base_x: ^2.0.1

  # State management
  provider: ^6.1.5+1

  # UI
  qr_flutter: ^4.1.0

  # Utils
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
